### ISSUE TITLE
Getting output from additional stacks

### ISSUE THREAD

**Issue by Lastin** [nordcloud/serverless-plugin-additional-stacks#24]
I got additional stack which creates DynamoDB table, and I need to use ARN of that table in my main primary stack to give the lambda some permissions.

How can I get `Outputs` from additional stack?

Thanks!

**Comment by kennu** [comment]
Hello. Unfortunately this is quite tricky, because Serverless will expand all variables, including [CloudFormation output references](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-cloudformation-outputs), before deploying the stack. So there probably isn't any good solution for referring to the outputs in your serverless.yaml.

**Comment by Lastin** [comment]
Thanks for the quick answer. Hardcoding the value was the only option in my case :)
